---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
concurrency:
  group: deploy

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      repository: "ha-addons"
      repository_beta: "ha-addons-beta"
      repository_edge: "ha-addons-edge"
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
    permissions:
      contents: write
      packages: write

  publish-stable:
    name: 📢 Publish to stable repository
    if: needs.information.outputs.environment == 'stable'
    needs:
      - workflows
    environment:
      name: ${{ needs.information.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Dispatch repository updater update signal
        uses: peter-evans/repository-dispatch@v2.1.2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.repository_owner }}/grott-home-assistant-add-on
          event-type: update
          client-payload: >
            {
              "addon": "${{ needs.information.outputs.slug }}",
              "name": "${{ needs.information.outputs.name }}",
              "repository": "${{ github.repository }}",
              "version": "${{ github.event.release.tag_name }}"
            }
