---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
concurrency:
  group: deploy

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      repository: "grott-home-assistant-add-on"
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
    permissions:
      contents: write
      packages: write
